import PaperActivityView from './PaperActivityView.jsx';
import { useState } from "react";
import { ChevronDown, Minus, MoreHorizontal, Plus } from "lucide-react";
import { parseNullableMarketNumber as number } from "../../utils/marketNumbers";
import { marketTimestamp, normalizeMarketQuote } from "../../utils/marketDataContract";

import { price, currency, signed, valueClass } from "./workstationFormat";

export function WorkstationTabs({ tabs, active, onChange, label }) {
  return <div className="ws-tabs" role="tablist" aria-label={label}>{tabs.map(tab => <button role="tab" aria-selected={active === tab.id} key={tab.id} onClick={() => onChange(tab.id)} onKeyDown={event => { if (["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) { event.preventDefault(); const index = tabs.findIndex(item => item.id === active); const next = event.key === "Home" ? 0 : event.key === "End" ? tabs.length - 1 : (index + (event.key === "ArrowRight" ? 1 : -1) + tabs.length) % tabs.length; onChange(tabs[next].id); event.currentTarget.parentElement.children[next]?.focus(); } }}>{tab.label}</button>)}</div>;
}

export function OrderBook({ quote = {} }) {
  const [tab, setTab] = useState("book");
  const meta = normalizeMarketQuote(quote);
  const reported = Boolean(meta.source && !meta.isSynthetic && !meta.fallback && !meta.degraded && meta.quality !== 'unavailable');
  // Only use provider-reported depth or BBO. Never infer a ladder from last price.
  const levels = reported && Array.isArray(quote.orderBook) ? quote.orderBook : [];
  const rows = levels.length ? levels : [reported ? { bid: quote.bidPrice ?? quote.bid, ask: quote.askPrice ?? quote.ask, bidSize: quote.bidSize, askSize: quote.askSize } : {}];
  const tape = reported && Array.isArray(quote.trades) ? quote.trades : [];
  const lastTime = marketTimestamp(quote.lastTradeTime);
  const snapshot = reported && lastTime && number(quote.lastTradePrice) > 0 && number(quote.lastTradeSize) > 0
    ? [{ time: lastTime, price: quote.lastTradePrice, size: quote.lastTradeSize }] : [];
  const trades = tape.length ? tape : snapshot;
  const timeLabel = time => new Date(time * 1000).toLocaleTimeString('en-US', { timeZone:'America/New_York', hour12:false });
  const detail = tab === 'book' ? (levels.length ? 'Provider depth' : 'Level 1 · best bid / ask') : tape.length ? 'Provider trade prints' : snapshot.length ? 'Last trade snapshot · not full tape' : 'Time & sales not connected';
  return <section className="ws-panel ws-order-book" aria-label="Order book">
    <div className="ws-panel-top"><WorkstationTabs tabs={[{ id:'book', label:'Order Book' }, { id:'tape', label:'Time & Sales' }]} active={tab} onChange={setTab} label="Market depth views" /></div>
    <div className="ws-table-scroll"><table><thead><tr>{(tab === 'book' ? ['Size','Bid','Ask','Size'] : ['Time (ET)','Price','Size','Exchange']).map((label,index) => <th key={`${label}-${index}`}>{label}</th>)}</tr></thead><tbody>{tab === 'book' ? rows.map((row,index) => <tr key={index}><td>{row.bidSize ?? '—'}</td><td className="ws-positive ws-bid-cell">{price(row.bid)}</td><td className="ws-negative ws-ask-cell">{price(row.ask)}</td><td>{row.askSize ?? '—'}</td></tr>) : trades.map((row,index) => <tr key={row.id || index}><td>{timeLabel(row.time)}</td><td>{price(row.price)}</td><td>{row.size}</td><td>{row.exchange || '—'}</td></tr>)}</tbody></table></div>
    <div className="ws-flow-status" title={tab === 'book' && !levels.length ? 'The connected quote feed reports Level 1 only. A separate provider feed is required for Level 2 depth.' : 'Snapshot polling reports the latest trade, not every execution. Missing prints and trade direction are not inferred.'}>{detail}<span>{meta.source || 'No provider'} · {meta.quality}{meta.asOf ? ` · ${timeLabel(meta.asOf)} ET` : ''}</span></div>
  </section>;
}

export function TradeTicket({ symbol, quote, quantity, setQuantity, onReview, defaultType = "LIMIT", setDefaultType }) {
  const [side, setSide] = useState("BUY");
  const [limit, setLimit] = useState("");
  const valid = Number.isInteger(Number(quantity)) && Number(quantity) > 0 && (defaultType === "MARKET" || limit === "" || number(limit) > 0);
  const referencePrice = defaultType === "MARKET" ? number(quote?.price) : number(limit) ?? number(quote?.price);
  return <section className="ws-panel ws-ticket" aria-label="Trade ticket"><div className="ws-tabs"><span className="ws-tab-active">Trade</span><span className="ws-muted" title="Options trading is not configured">Options</span><span className="ws-muted" title="Use the full order review for advanced settings">Advanced</span></div><div className="ws-ticket-body"><div className="ws-side-toggle">{["BUY", "SELL"].map(value => <button key={value} className={side === value ? value === "BUY" ? "is-buy" : "is-sell" : ""} aria-pressed={side === value} onClick={() => setSide(value)}>{value === "BUY" ? "Buy" : "Sell"}</button>)}</div><label className="ws-order-type"><span className="sr-only">Order type</span><select aria-label="Dashboard order type" value={defaultType} onChange={event => setDefaultType?.(event.target.value)}><option value="MARKET">Market</option><option value="LIMIT">Limit</option><option value="STOP">Stop</option></select><ChevronDown size={13} /></label><div className="ws-ticket-field"><label htmlFor="ws-quantity">Quantity</label><div className="ws-quantity"><input id="ws-quantity" aria-label="Dashboard order quantity" type="number" step="1" min="1" value={quantity ?? ""} onChange={event => setQuantity?.(event.target.value === "" ? "" : Number(event.target.value))} /><button aria-label="Decrease quantity" onClick={() => setQuantity?.(Math.max(1, Number(quantity) - 1))}><Minus size={14} /></button><button aria-label="Increase quantity" onClick={() => setQuantity?.(Math.max(0, Number(quantity)) + 1)}><Plus size={14} /></button></div></div><div className="ws-ticket-field"><label htmlFor="ws-limit">{defaultType === "MARKET" ? "Reference" : defaultType === "STOP" ? "Stop Price" : "Limit Price"}</label><input id="ws-limit" type="number" min="0.01" step="0.01" placeholder={price(quote?.price)} value={defaultType === "MARKET" ? quote?.price ?? "" : limit} readOnly={defaultType === "MARKET"} onChange={event => setLimit(event.target.value)} /></div><div className="ws-ticket-field"><span>Est. notional</span><strong>{valid && referencePrice !== null ? currency(Number(quantity) * referencePrice) : "—"}</strong></div><button className={`ws-order-button ${side === "SELL" ? "is-sell" : ""}`} disabled={!valid} onClick={() => onReview?.(side, symbol, { type: defaultType, price: defaultType === "MARKET" ? null : number(limit) })}>Review {side === "BUY" ? "Buy" : "Sell"} Order</button><small className="ws-muted">No order is submitted from this ticket.</small></div></section>;
}

export function PortfolioTable({ trading, positions = [], orders = [], onSelect, onOrders, onPositions, onJournal, notes, setNotes }) {
  const [tab, setTab] = useState("positions");
  const tabs = [{ id: "positions", label: `Positions (${positions.length})` }, { id: "orders", label: `Orders (${orders.length})` }, { id: "executions", label: "Executions" }, { id: "pnl", label: "P&L" }, { id: "log", label: "Day Trade Log" }, { id: "notes", label: "Notes" }];
  const change = id => { setTab(id); };
  return <section className="ws-panel ws-portfolio" aria-label="Portfolio records"><WorkstationTabs tabs={tabs} active={tab} onChange={change} label="Portfolio views" /><div className="ws-table-scroll">{tab === "positions" ? <table><thead><tr>{["Symbol", "Qty", "Avg Price", "Last", "Unrealized P&L", "%", "Day P&L", "Actions"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{positions.map(row => <tr key={row.symbol}><td><button className="ws-symbol-link" onClick={() => onSelect?.(row.symbol)}>{row.symbol}</button></td><td>{row.qty ?? "—"}</td><td>{price(row.avg)}</td><td>{price(row.last)}</td><td className={valueClass(row.unrealizedPnl)}>{signed(row.unrealizedPnl)}</td><td className={valueClass(row.unrealizedPnl)}>{row.avg > 0 && row.qty && row.unrealizedPnl !== null ? `${signed(row.unrealizedPnl / Math.abs(row.avg * row.qty) * 100)}%` : "—"}</td><td className={valueClass(row.dayPnl)}>{signed(row.dayPnl)}</td><td><button className="ws-icon" aria-label={`Review ${row.symbol} position`} onClick={() => { onSelect?.(row.symbol); onOrders?.(); }}><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table> : tab === "orders" ? <table><thead><tr>{["Symbol", "Side", "Qty", "Type", "Price", "Status", "Actions"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{orders.map((row, index) => <tr key={row.id || index}><td>{row.symbol}</td><td className={row.side === "BUY" ? "ws-positive" : "ws-negative"}>{row.actionLabel || (row.action || row.side)?.replaceAll('_', ' ')}</td><td>{row.qty ?? row.quantity ?? "—"}</td><td>{row.type || row.orderType || "—"}</td><td>{price(row.price)}</td><td>{row.status}</td><td><button className="ws-icon" aria-label={`Review order ${row.symbol}`} onClick={onOrders}><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table> : trading && ["executions", "pnl", "log"].includes(tab) ? <PaperActivityView trading={trading} tab={tab} /> : tab === "notes" ? <textarea aria-label="Dashboard notes" placeholder="Write your session notes..." value={notes || ""} onChange={event => setNotes?.(event.target.value)} /> : <div className="ws-data-empty"><p>{tab === "executions" ? "Verified executions are available through the order workspace." : tab === "pnl" ? "Review complete P&L and source details in Positions." : "Open your journal to review recorded trades."}</p><button onClick={tab === "log" ? onJournal : tab === "pnl" ? onPositions : onOrders}>Open {tab === "log" ? "Journal" : "workspace"} ↗</button></div>}{tab === "positions" && !positions.length && <div className="ws-data-empty">No workspace positions.</div>}</div></section>;
}

export function DashboardNews({ news = [], alerts = [], toggleAlert, openNews, openAlerts }) {
  const [tab, setTab] = useState("news");
  return <section className="ws-panel ws-news" aria-label="Market news"><WorkstationTabs label="News views" tabs={[{ id: "news", label: "News" }, { id: "calendar", label: "Economic Calendar" }, { id: "alerts", label: "Alerts" }]} active={tab} onChange={setTab} /><div className="ws-news-scroll">{tab === "news" ? news.map((row, index) => <button className="ws-news-row" key={row.id || index} onClick={() => openNews?.(row)}><time>{row.time || "—"}</time><span>{row.headline || row.title}</span><b>{row.symbol || row.relatedTicker || "Market"}</b><small>{row.source || "Provider"}</small></button>) : tab === "alerts" ? alerts.map(row => <div className="ws-alert-row" key={row.id}><button onClick={openAlerts}>{row.symbol} {row.direction} {price(row.trigger)}</button><button role="switch" aria-checked={row.active} aria-label={`Monitor ${row.symbol}`} onClick={() => toggleAlert?.(row.id)}>{row.active ? "On" : "Off"}</button></div>) : <div className="ws-data-empty">No verified economic calendar is connected.</div>}{tab === "news" && !news.length && <div className="ws-data-empty">No provider headlines available.</div>}{tab === "alerts" && !alerts.length && <div className="ws-data-empty"><button onClick={openAlerts}>Create a price alert ↗</button></div>}</div></section>;
}
