import { test, expect } from '@playwright/test';
import { setupApp, initialWorkspace, user } from '../support/appHarness.js';
const now = Date.parse('2026-10-08T15:00:00Z');
const quotes = [{ symbol: 'AAPL', price: 100, source: 'Isolated test provider', timestamp: now / 1000 }];
const navigate = async (page, name, width) => {
  if (width < 800) await page.getByRole('button', { name: 'Open workspace navigation' }).click();
  await page.getByRole('navigation', { name: 'Terminal workspaces' }).getByRole('button', { name, exact: true }).click();
};
test('journal invalid trade risk does not block a note, and manual discipline fields survive reload', async ({ page }) => {
  await page.clock.setFixedTime(now);
  const evidence = await setupApp(page, { ...initialWorkspace, activeWorkspace: 'journal', journalEntries: [] });
  await page.getByLabel('Journal setup', { exact: true }).fill('Manual risk review');
  await page.getByLabel('Journal record type').selectOption('trade');
  await page.getByLabel('Journal planned risk', { exact: true }).fill('-1');
  const save = page.getByRole('button', { name: 'Save Record', exact: true });
  await expect(save).toBeDisabled();
  await page.getByLabel('Journal record type').selectOption('note'); await expect(save).toBeEnabled();
  await page.getByLabel('Journal record type').selectOption('trade'); await expect(save).toBeDisabled();
  await page.getByLabel('Journal planned risk', { exact: true }).fill('5');
  await page.getByLabel('Journal recorded checklist').selectOption('incomplete');
  await page.getByLabel('Journal mistake tags').fill('late entry, chase');
  await page.getByLabel('Journal quantity', { exact: true }).fill('1');
  await page.getByLabel('Journal entry price', { exact: true }).fill('100');
  await page.getByLabel('Journal exit price', { exact: true }).fill('90');
  await page.getByLabel('Journal total fees', { exact: true }).fill('0');
  await save.click();
  await expect.poll(() => evidence.workspace().journalEntries?.[0]?.plannedRiskAmount).toBe(5);
  await page.reload(); await page.getByRole('tab', { name: 'Statistics', exact: true }).click();
  await page.getByLabel('Journal analysis dimension').selectOption('risk');
  await expect(page.getByRole('row', { name: 'Select Loss exceeded planned risk', exact: true })).toContainText('-2.00R');
  await page.getByLabel('Journal analysis dimension').selectOption('checklist');
  await expect(page.getByRole('row', { name: 'Select Recorded incomplete', exact: true })).toBeVisible();
  expect(evidence.errors).toEqual([]); expect(evidence.blocked).toEqual([]);
});
for (const width of [390, 1536]) test(`cost-aware ticket rejects above budget and journals the actual entry plan at ${width}px`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 1024 }); await page.clock.setFixedTime(now);
  const evidence = await setupApp(page, { ...initialWorkspace, selectedStock: 'AAPL', activeWorkspace: 'settings', layoutMode: '1', positions: {}, orders: [], journalEntries: [], premiumPreferences: { paperCosts: { commissionPerOrder: 1, commissionPerShare: .01, slippageBps: 10 } } }, { providerQuotes: quotes });
  await page.getByRole('tab', { name: 'Trading', exact: true }).click();
  await page.getByLabel('Risk per trade ($)', { exact: true }).fill('14'); await page.getByRole('button', { name: 'Save Paper Rules', exact: true }).click();
  await expect.poll(() => evidence.workspace().paperLedger?.riskPolicy?.riskPerTrade).toBe(14);
  await navigate(page, 'Dashboard', width); const ticket = page.getByRole('region', { name: 'Paper trade ticket', exact: true });
  await ticket.getByLabel('Paper order type').selectOption('MARKET');
  await ticket.getByLabel('Paper quantity').fill('10'); await ticket.locator('summary').click(); await ticket.getByLabel('Stop loss', { exact: true }).fill('99');
  await expect(ticket.getByLabel('Planned paper risk')).toContainText('$14.19');
  await ticket.getByRole('button', { name: 'Place Paper Buy', exact: true }).click(); await expect(ticket.getByRole('status')).toContainText('planned loss $14.19 > $14.00');
  expect(evidence.workspace().paperLedger.orders).toHaveLength(0);
  await navigate(page, 'Settings', width); await page.getByRole('tab', { name: 'Trading', exact: true }).click();
  await page.getByLabel('Risk per trade ($)', { exact: true }).fill('15'); await page.getByRole('button', { name: 'Save Paper Rules', exact: true }).click();
  await expect.poll(() => evidence.workspace().paperLedger.riskPolicy.riskPerTrade).toBe(15);
  await navigate(page, 'Dashboard', width); await ticket.getByLabel('Paper quantity').fill('10'); await ticket.locator('summary').click(); await ticket.getByLabel('Stop loss', { exact: true }).fill('99');
  await ticket.getByRole('button', { name: 'Place Paper Buy', exact: true }).click(); await expect(ticket.getByRole('status')).toContainText('FILLED');
  await expect.poll(() => evidence.workspace().paperLedger.positions.AAPL?.plannedRiskRemaining).toBe(14.19);
  await page.screenshot({ path: info.outputPath('cost-aware-risk.png'), fullPage: true }); expect(evidence.errors).toEqual([]); expect(evidence.blocked).toEqual([]);
});
for (const width of [390, 1536]) test(`alert diagnostics show per-rule quote evidence and stale waiting after reload at ${width}px`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 1024 }); await page.clock.setFixedTime(now);
  const providerQuotes = [...quotes];
  const evidence = await setupApp(page, { ...initialWorkspace, activeWorkspace: 'alerts', selectedStock: 'AAPL', alerts: [{ id: 'watch', symbol: 'AAPL', trigger: 1000, direction: 'above', active: true }] }, { providerQuotes });
  const monitoring = page.getByLabel('Enable background price alerts'); await expect(monitoring).toBeEnabled(); await monitoring.click(); await expect(monitoring).toBeChecked(); await page.reload();
  await page.getByRole('row', { name: 'Select AAPL', exact: true }).click();
  const diagnostics = page.getByLabel('Selected alert diagnostics'); await expect(diagnostics).toContainText('Watching target');
  await expect(diagnostics).toContainText('Isolated test provider'); await expect(diagnostics).toContainText('Last valid live quote');
  providerQuotes[0] = { ...quotes[0], timestamp: now / 1000 - 60 }; await evidence.alertService.tick(); await page.reload();
  await page.getByRole('row', { name: 'Select AAPL', exact: true }).click();
  await expect(diagnostics).toContainText('Waiting for fresh data'); await expect(diagnostics).toContainText('Quote stale');
  expect((await evidence.alertService.snapshot(user.id)).alerts[0].history).toHaveLength(0);
  await page.screenshot({ path: info.outputPath('alert-evidence.png'), fullPage: true }); expect(evidence.errors).toEqual([]); expect(evidence.blocked).toEqual([]);
});
for (const width of [390, 1536]) test(`journal discipline comparisons preserve grouped risk and unknowns at ${width}px`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 1024 }); await page.clock.setFixedTime(now);
  const record = extra => ({ id: 'one', symbol: 'AAPL', recordType: 'trade', status: 'closed', createdAt: '2026-10-08T15:00Z', pnl: -4, plannedRiskAmount: 4, source: 'Paper simulation', tradeGroupId: 'plan', quantity: 4, entryChecklistStatus: 'complete', setup: 'Breakout', ...extra });
  const evidence = await setupApp(page, { ...initialWorkspace, activeWorkspace: 'journal', journalEntries: [record({}), record({ id: 'last', pnl: -8, quantity: 6, plannedRiskAmount: 6, closesPosition: true }), record({ id: 'legacy', source: 'Manual journal', tradeGroupId: null, pnl: 1, plannedRiskAmount: null, entryChecklistStatus: 'unknown', mistakeTags: 'late entry, chase' })] });
  await page.getByRole('tab', { name: 'Statistics', exact: true }).click(); const dimension = page.getByLabel('Journal analysis dimension');
  await dimension.selectOption('risk'); const loss = page.getByRole('row', { name: 'Select Loss exceeded planned risk', exact: true });
  await expect(loss).toContainText('$10.00'); await expect(loss).toContainText('$12.00'); await expect(loss).toContainText('-1.20R');
  await expect(page.getByRole('row', { name: 'Select Planned risk unknown', exact: true })).toContainText('Unavailable');
  await dimension.selectOption('checklist'); await expect(page.getByRole('row', { name: 'Select Recorded complete', exact: true })).toContainText('$10.00');
  await dimension.selectOption('mistakes'); await expect(page.getByRole('cell', { name: 'late entry', exact: true })).toBeVisible(); await expect(page.getByRole('cell', { name: 'chase', exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath('journal-discipline.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); expect(evidence.errors).toEqual([]); expect(evidence.blocked).toEqual([]);
});
